services:
    main:
        image: ghcr.io/plfanzen/demo-chal:main
        external_ports:
            - port: 3000
              protocol: TCP # Alternatively, TCP is supported

metadata:
    name: Socket Test
    description_md: |
        Just testing socket stuff.
    difficulty: "easy"
    base_points: 100
    categories:
        - misc
    authors:
        - Aaron
        - Plfanzen
    flag: PLFANZEN{TEST_SVC_2}

volumes: {}
